language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
  - secure: XUpChpkkgcijBXEDcQLdItlLyuLQrssd/WE4sFx60VcRliWDdWwA/nHr+1unOG1RQtMgDtkgFp2vHXlF/YZYHVYR7Z/sQfSQtQYnRyvru9H8GLxmr4rqOkuZkcshwcjvZaMMvpYH8Mno5fGDEWyYURyr+QogV0KORaWZ7OIrw4H9hxnxe4BQL1sH4sgf8XTUw4iaPesSGc49+dpUM0qRyabEZxKLUzKcCjlD8zP4BxxQFAtJ/YUcmODeI7fqY4uHVyTHryKXupm9+n2Wv7cibsp2Z7VabQoyVNN1Y0JhAnq2bN583uQJoO8jZhj59PwRn6ujwEDoCz3duR5jFbLbeMgftpNTgcfjieqGOoVgLjWEOElZBiEht7nhClRcsDxV24r9wEUA/tnyEfrP2bKMQ6jkdlE4wfeNE/3wTEsnkEhjJXqeqD7GenhEjx8nZIZkhX1EQMYaalg8WQ5TIsF9764IwlT8AnT4++e+j6qmtyh7vdkFhSgMEtOFmQs7rsPwQmvzxToEEfeG+93fm/UR+zFFhY43x8rZwnYcKNI5Sihtux9zZTyQ+0Kj4Kq3zVN/mFLdjWSu9zR1YeRTCQ9yMyrhWO1HogLuXcnVCAG3JEiiqyQfBOKiy9CaxTKIDAdjNkBy+D1mS9CrlmVzwvMrVGIztl0XMJoW3oieirUbtqw=
  - secure: MQEYztGyHnYc8At50wc+uMtC7J6Ehs0l4U0vtCm5HmB6jz7jtHpteUCkTzIeB0vB4mAdkzlf2nxG+j4rGxtaWgfaqin1qmZx4gMEMLOMYiZMFHjEkUDvsSaOLacCAwo1e7eW8ToxcCIV9F2Um8qSLCH4olpPkdE4yxX1mfD4k4DrSl23dnfEzOdonyEdJYUOH50fvh9AAO0z/VM+xI9Xm0brJgM3qiQTeh1EB9eOId5J6b9y9UitLl5bY3rOHkuHGhTR5IrlTHxW9hd5CgTRTakyoLmoNkWYnSeTS6h4tCdHzkS7wTfpQHm3ZL3l+HhSVOc9hLqdD4tsRREpXQAZup2RTblaFvPe+brvDvd2RjIPXjelUV9Ggj2AdiNF8uNxoy1tV9CNMdwomJLPi2/T8bVroy6qr4SiUM7VQt4TuCDsnYPj9GkE/IdK0nVKu5SfxDCQrGdmphXnquOrwpo1sYArnnsA4xe38yqi5Sh9X61Puln2AOH/yQIdFg+4wm7TPBpbm9mYMj94N1rwzUKM7cwKwHyHNL+WujHPqXR33jlJW/XhNjLdbeD4qWCk/You5nU2YGjaR0qnzQtoiIXjrqCi4sxQiIEukV8/ecEndAIhnWsc4ElG4NLOya55GxjsW2aq95VLpN5eBJ1ZgdnLWVjvRN6wBalsPKkabGGXyN0=

before_install:
  - composer self-update

before_script:
  - composer install

script:
  - composer test